### ISSUE TITLE
Use group CSS selectors to reduce your code

### ISSUE THREAD

**Issue by kostasx** [safeplace12345/Google#10]
For example:
https://github.com/safeplace12345/Google/blob/0f7374aff9bad068a8146dd101020a8f568ce1e0/main.css#L30

This code:

```css
nav>div:nth-child(1) {
    width: 100px;
    display: flex;
    justify-content: space-around;

}

nav>div:nth-child(2) {
    width: 100px;
    display: flex;
    justify-content: space-around;
}
```

Can become:

```css
nav>div:nth-child(1),
nav>div:nth-child(2) {
    width: 100px;
    display: flex;
    justify-content: space-around;

}
```
